In [19]:
# #!/usr/bin/env python

# import cv2
# import numpy as np

# # Read Image
# im = cv2.imread("headPose.jpg");
# size = im.shape
    
# #2D image points. If you change the image, you need to change vector
# image_points = np.array([
#                             (359, 391),     # Nose tip
#                             (399, 561),     # Chin
#                             (337, 297),     # Left eye left corner
#                             (513, 301),     # Right eye right corne
#                             (345, 465),     # Left Mouth corner
#                             (453, 469)      # Right mouth corner
#                         ], dtype="double")

# # 3D model points.
# model_points = np.array([
#                             (0.0, 0.0, 0.0),             # Nose tip
#                             (0.0, -330.0, -65.0),        # Chin
#                             (-225.0, 170.0, -135.0),     # Left eye left corner
#                             (225.0, 170.0, -135.0),      # Right eye right corne
#                             (-150.0, -150.0, -125.0),    # Left Mouth corner
#                             (150.0, -150.0, -125.0)      # Right mouth corner
                        
#                         ])


# # Camera internals

# focal_length = size[1]
# center = (size[1]/2, size[0]/2)
# camera_matrix = np.array(
#                          [[focal_length, 0, center[0]],
#                          [0, focal_length, center[1]],
#                          [0, 0, 1]], dtype = "double"
#                          )

# print "Camera Matrix :\n {0}".format(camera_matrix)

# dist_coeffs = np.zeros((4,1)) # Assuming no lens distortion
# (success, rotation_vector, translation_vector) = cv2.solvePnP(model_points, image_points, camera_matrix, dist_coeffs, flags=cv2.CV_ITERATIVE)

# print "Rotation Vector:\n {0}".format(rotation_vector)
# print "Translation Vector:\n {0}".format(translation_vector)


# # Project a 3D point (0, 0, 1000.0) onto the image plane.
# # We use this to draw a line sticking out of the nose


# (nose_end_point2D, jacobian) = cv2.projectPoints(np.array([(0.0, 0.0, 1000.0)]), rotation_vector, translation_vector, camera_matrix, dist_coeffs)

# for p in image_points:
#     cv2.circle(im, (int(p[0]), int(p[1])), 3, (0,0,255), -1)


# p1 = ( int(image_points[0][0]), int(image_points[0][1]))
# p2 = ( int(nose_end_point2D[0][0][0]), int(nose_end_point2D[0][0][1]))

# cv2.line(im, p1, p2, (255,0,0), 2)

# # Display image
# cv2.imshow("Output", im)
# cv2.waitKey(0)

# Perform one image calculation

https://www.learnopencv.com/head-pose-estimation-using-opencv-and-dlib/

In [20]:
import cv2
import numpy as np

In [21]:
# Read Image
im = cv2.imread("headPose.jpg");
size = im.shape

In [22]:
#2D image points. If you change the image, you need to change vector
image_points = np.array([
                            (359, 391),     # Nose tip
                            (399, 561),     # Chin
                            (337, 297),     # Left eye left corner
                            (513, 301),     # Right eye right corne
                            (345, 465),     # Left Mouth corner
                            (453, 469)      # Right mouth corner
                        ], dtype="double")

In [23]:
# 3D model points.
model_points = np.array([
                            (0.0, 0.0, 0.0),             # Nose tip
                            (0.0, -330.0, -65.0),        # Chin
                            (-225.0, 170.0, -135.0),     # Left eye left corner
                            (225.0, 170.0, -135.0),      # Right eye right corne
                            (-150.0, -150.0, -125.0),    # Left Mouth corner
                            (150.0, -150.0, -125.0)      # Right mouth corner
                        
                        ])

In [24]:
# Camera internals
focal_length = size[1]
center = (size[1]/2, size[0]/2)
camera_matrix = np.array(
                         [[focal_length, 0, center[0]],
                         [0, focal_length, center[1]],
                         [0, 0, 1]], dtype = "double"
                         )

print("Camera Matrix :\n {0}".format(camera_matrix))

dist_coeffs = np.zeros((4,1)) # Assuming no lens distortion

Camera Matrix :
 [[1.200e+03 0.000e+00 6.000e+02]
 [0.000e+00 1.200e+03 3.375e+02]
 [0.000e+00 0.000e+00 1.000e+00]]


In [25]:
# PnP solution
(success, rotation_vector, translation_vector) = cv2.solvePnP(model_points, image_points, camera_matrix, dist_coeffs, flags=cv2.cv2.SOLVEPNP_ITERATIVE)

print("Rotation Vector:\n {0}".format(rotation_vector))
print("Translation Vector:\n {0}".format(translation_vector))

Rotation Vector:
 [[-0.05800198]
 [ 2.20224639]
 [ 0.01942058]]
Translation Vector:
 [[  449.51968738]
 [  -94.74161089]
 [-2343.96945188]]


In [26]:
# Project a 3D point (0, 0, 1000.0) onto the image plane.
# We use this to draw a line sticking out of the nose

(nose_end_point2D, jacobian) = cv2.projectPoints(np.array([(0.0, 0.0, 1000.0)]), rotation_vector, translation_vector, camera_matrix, dist_coeffs)

for p in image_points:
    cv2.circle(im, (int(p[0]), int(p[1])), 3, (0,0,255), -1)


p1 = ( int(image_points[0][0]), int(image_points[0][1]))
p2 = ( int(nose_end_point2D[0][0][0]), int(nose_end_point2D[0][0][1]))

cv2.line(im, p1, p2, (255,0,0), 2)

# Display image
cv2.imshow("Output", im)
cv2.waitKey(0)

-1

# PnP applied to cone

In [9]:
# Read Image
im = cv2.imread("amz_00004.jpg");
size = im.shape
size

(740, 940, 3)

In [10]:
cv2.imshow("Input", im)
cv2.waitKey(0)

-1

In [11]:
#2D image points. If you change the image, you need to change vector
image_points = np.array([
                            (600, 445),     # A
                            (597, 455),     # B
                            (604, 455),     # C
                            (596, 462),     # D
                            (606, 462),     # E
                            (595, 470),     # F
                            (608, 470),     # G
                        ], dtype="double")

In [12]:
# 3D model points.
model_points = np.array([
                            (0.0, 0.0, 325),# A
                            (0.0, -11.5, 223.4),# B
                            (0, 11.5, 223.4),# C
                            (0, -22.6, 131.1),# D
                            (0, -22.6, 131.1),# E
                            (0, -35, 25),# F
                            (0, 35, 25), # G
                        ])

In [13]:
# Camera internals
focal_length = size[1]
center = (size[1]/2, size[0]/2)
camera_matrix = np.array(
                         [[focal_length, 0, center[0]],
                         [0, focal_length, center[1]],
                         [0, 0, 1]], dtype = "double"
                         )

print("Camera Matrix :\n {0}".format(camera_matrix))

dist_coeffs = np.zeros((4,1)) # Assuming no lens distortion

Camera Matrix :
 [[940.   0. 470.]
 [  0. 940. 370.]
 [  0.   0.   1.]]


In [14]:
# methods = [cv2.cv2.SOLVEPNP_ITERATIVE, cv2.cv2.SOLVEPNP_P3P, cv2.cv2.SOLVEPNP_EPNP,
#            cv2.cv2.SOLVEPNP_DLS]

# for method in methods:
#     print("\n", method)
#     (success, rotation_vector, translation_vector) = cv2.solvePnP(model_points, image_points, camera_matrix, dist_coeffs, flags=method)

#     print("Success?", success)
#     print("Rotation Vector:\n {0}".format(rotation_vector))
#     print("Translation Vector:\n {0}".format(translation_vector))

In [15]:
# PnP solution
(success, rotation_vector, translation_vector) = cv2.solvePnP(model_points, image_points, camera_matrix, dist_coeffs, flags=cv2.cv2.SOLVEPNP_ITERATIVE)

print("Success?", success)
print("Rotation Vector:\n {0}".format(rotation_vector))
print("Translation Vector:\n {0}".format(translation_vector))

Success? True
Rotation Vector:
 [[ 1.88682602]
 [ 1.94351276]
 [-0.80653627]]
Translation Vector:
 [[ 863.43276593]
 [ 663.55007664]
 [6101.82476303]]


In [16]:
# # PnP RANSAC solution
# (rotation, translation, inliers) = cv2.solvePnPRansac(model_points, image_points, camera_matrix, dist_coeffs, flags=cv2.cv2.SOLVEPNP_ITERATIVE)

# print("Inlier indices?", inliers)v
# print("Rotation Vector:\n {0}".format(rotation))
# print("Translation Vector:\n {0}".format(translation))

In [18]:
# Project a 3D point (0, 0, 1000.0) onto the image plane.
# We use this to draw a line sticking out of the nose
im_to_draw = im.copy()

(x_axis, jacobian) = cv2.projectPoints(np.array([(1000.0, 0.0, 0.0)]), rotation_vector, translation_vector, camera_matrix, dist_coeffs)
(y_axis, jacobian) = cv2.projectPoints(np.array([(0.0, 1000.0, 0.0)]), rotation_vector, translation_vector, camera_matrix, dist_coeffs)
(z_axis, jacobian) = cv2.projectPoints(np.array([(0.0, 0.0, 1000.0)]), rotation_vector, translation_vector, camera_matrix, dist_coeffs)

for p in image_points:
    cv2.circle(im_to_draw, (int(p[0]), int(p[1])), 3, (0,0,255), -1)


center_point = ( int(image_points[0][0]), int(image_points[0][1]))
x_axis_point = ( int(x_axis[0][0][0]), int(x_axis[0][0][1]))
y_axis_point = ( int(y_axis[0][0][0]), int(y_axis[0][0][1]))
z_axis_point = ( int(z_axis[0][0][0]), int(z_axis[0][0][1]))

cv2.line(im_to_draw, center_point, x_axis_point, (255,0,0), 2) # Blue
cv2.line(im_to_draw, center_point, y_axis_point, (0,255,0), 2) # Green
cv2.line(im_to_draw, center_point, z_axis_point, (0,0,255), 2) # Red

# Display image
cv2.imwrite("amz_00004_annotated.jpg", im_to_draw)
cv2.imshow("Output", im_to_draw)
cv2.waitKey(0)

-1